#define	I_SPEAK "ÎÒËµÖĞÎÄ."
#define	L001(a,b) S("PRIVMSG %s : Äã»¹Ã»ÓĞÉèÖÃ¿ÚÁî. ÒªÉèÖÃ¿ÚÁî,Çë´ò: \2/msg %s PASS \
<¾É¿ÚÁî> <ĞÂ¿ÚÁî>\2 (Èç¹ûÊÇµÚÒ»´ÎÉèÖÃ¿ÚÁî,¾É¿ÚÁîÓ¦ÌîÎª 0 )\n",a,b)
#define	L002(a,b,c) S("NOTICE %s :ÒÑ³É¹¦É¾³ı½ûÓÃÓÃ»§ #%d, %s.\n",a,b,c)
#define	L003(a,b) S("NOTICE %s :ÎŞ·¨´ò¿ª%s :(\n",a,b)
#define L004(a,b,c) S("PRIVMSG %s :%s, ÔÚÎÒµÄÊı¾İ¿âÀïÒ»¹²ÓĞ%dÌõÀúÊ·ÓÃ»§¼ÇÂ¼.\n",a,b,c)
#define	L005(a,b) S("PRIVMSG %s :ÄãÒÑ¾­ÖªµÀµÃ±ÈÎÒ¶àÁË, %s.\n",a,b)
#define	L006(a,b,c,d) S("PRIVMSG %s :%s, ÎÒÃ»ÓĞ¼û¹ı%s %s\n",a,b,c,d)
#define	L007(a,b) S("NOTICE %s :×Ô¶¯Ö÷Ìâ %s ¸Õ²ÅÊÇ¹Ø±ÕµÄ\n",a,b)
#define	L008(a,b) S("NOTICE %s :×Ô¶¯Ö÷Ìâ %s ÏÖÔÚ¹Ø±Õ\n",a,b);
#define	L009(a,b,c) S("NOTICE %s :×Ô¶¯Ö÷Ìâ@ %s ´ò¿ª: %s\n",a,b,c)
#define	L010(a,b,c) S("NOTICE %s :×Ô¶¯Ö÷Ìâ@ %s ÒÑ¸üĞÂ: %s\n",a,b,c)
#define	L011(a,b,c) S("PRIVMSG %s :%s, ÒÑÍê³É. ÏÖ¹²ÓĞ %d ÌõËæ»úÄÚÈİ.\n",a,b,c)
#define	L012(a,b) S("NOTICE %s :%sµÄ¿ÚÁîÒÑ¸üĞÂ.\n",a,b)
#define	L013(a) S("NOTICE %s :¿ÚÁî´íÎó!\n",a)
#define	L014(a) S("NOTICE %s :ÎŞÆ¥Åä¼ÇÂ¼!\n",a)
#define	L015(a,b,c,d) S("NOTICE %s :ÓÃ»§ÒÑÉ¾³ı: %s [%d:%d]\n",a,b,c,d)
#define	L016(a,b) S("PRIVMSG %s :%s: ±»Áã³ı´íÎó!\n",a,b)
#define	L017(a,b) S("PRIVMSG %s :%s: ·Ç·¨²Ù×÷!\n",a,b)
#define	L018(a,b,c,d,e) S("KICK %s %s :%s (Ôö¼Ó×Ô¶¯ºöÂÔÓÃ»§#%d: %s)\n",a,b,c,d,e)
#define	L019(a,b,c) S("PRIVMSG %s :Ôö¼Ó×Ô¶¯ºöÂÔÓÃ»§#%d: %s!\n",a,b,c);
#define L020(a,b,c,d) S("NOTICE %s :ÒÑ¸üĞÂ #%d: \37[\37%s\37]\37 info\2:\2 %s\n",a,b,c,d)
#define	L021(a,b,c,d) S("PRIVMSG %s :%s \37%s\37.. %d Ìõ¼ÇÂ¼ÒÑËÑË÷.\n",a,b,c,d)
#define	L022(a,b,c) S("PRIVMSG %s :ÒÑ·¢ÏÖ³¬¹ı\37%d\37 ÌõÆ¥Åä¼ÇÂ¼, ÇëÊäÈë¸ü¶àÌõ¼şÒÔËõĞ¡ËÑË÷·¶Î§\2:\2 \
%s\n",a,b,c);
#define	L023(a,b,c) S("PRIVMSG %s :ÎÒÕÒµ½ \37Ò»Ìõ\37 ·ûºÏÌõ¼şµÄ¼ÇÂ¼, %s\2:\2 %s\n",a,b,c)
#define	L024(a,b,c,d) S("PRIVMSG %s :ÎÒÕÒµ½\37%d\37 Ìõ·ûºÏÌõ¼şµÄ¼ÇÂ¼, %s\2:\2 %s\n",a,b,c,d)
#define	L025(a,b) S("PRIVMSG %s :ÕÒµ½%ldÌõÖØ¸´¼ÇÂ¼,ÒÑÉ¾³ı.\n",a,b)
#define	L026(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :ÕıÔÚÔËĞĞ %s. ÎÒµÄÊı¾İ¿âÖĞÓĞ%ldÌõ¼ÇÂ¼, ÒÑÔËĞĞÊ±¼ä: \
%d Ìì%s, %02d:%02d, ±»ÌáÎÊ%ld´Î, Ôö¼Ó%ldÌõ¼ÇÂ¼, É¾³ı%ldÌõ¼ÇÂ¼. \
´¦ÀíÊ±¼ä: %1.4lf Ãë%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define	L027(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :ÕıÔÚÔËĞĞ %s. ÎÒµÄÊı¾İ¿âÖĞÓĞ%ldÌõ¼ÇÂ¼, ÒÑÔËĞĞÊ±¼ä: \
%d Ğ¡Ê±%s, %d ·ÖÖÓ%s, ±»ÌáÎÊ%ld´Î, Ôö¼Ó%ldÌõ¼ÇÂ¼, É¾³ı%ldÌõ¼ÇÂ¼. \
´¦ÀíÊ±¼ä: %1.4lf Ãë%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define	L028(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :ÕıÔÚÔËĞĞ %s. ÎÒµÄÊı¾İ¿âÖĞÓĞ%ldÌõ¼ÇÂ¼, ÒÑÔËĞĞÊ±¼ä: \
%d ·ÖÖÓ%s, %d Ãë%s, ±»ÌáÎÊ%ld´Î, Ôö¼Ó%ldÌõ¼ÇÂ¼, É¾³ı%ldÌõ¼ÇÂ¼. \
´¦ÀíÊ±¼ä: %1.4lf Ãë%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define	L029(a,b,c,d) S("PRIVMSG %s :%s: ÎÒÒÑÉ¾³ıÁË¼ÇÂ¼#%ld, \2%s\2.\n",a,b,c,d)
#define	L030(a,b,c) S("PRIVMSG %s :%s\2:\2 ÕÒ²»µ½¼ÇÂ¼%s. É¾³ıÊ§°Ü.\n",a,b,c)
#define	L029n(a,b,c,d) S("NOTICE %s :%s: ÎÒÒÑÉ¾³ıÁË¼ÇÂ¼#%ld, \2%s\2.\n",a,b,c,d)
#define	L030n(a,b,c) S("NOTICE %s :%s\2:\2 ÕÒ²»µ½¼ÇÂ¼%s. É¾³ıÊ§°Ü.\n",a,b,c)
#define	L031(a,b) S("NOTICE %s :ÓÃ·¨: \2/msg %s PASS <¾É¿ÚÁî> <ĞÂ¿ÚÁî>\2\n",a,b)
#define	L032(a)	Snow("QUIT :K\2\2illed (%s (cause I say so!))\n",a)
#define	L033(a)	S("NOTICE %s :ÓÃ·¨: UP <#ÆµµÀ> <¿ÚÁî>\n",a)
#define	L034(a)	S("NOTICE %s :ÓÃ·¨: OP <#ÆµµÀ> [êÇ³Æ] <¿ÚÁî>\n",a)
#define	L035(a)	S("NOTICE %s :ÓÃ·¨: DEOP <#ÆµµÀ> [êÇ³Æ] <¿ÚÁî>\n",a)
#define	L036(a)	S("NOTICE %s :ÇëÖ¸¶¨Ò»¸öêÇ³Æ!\n",a)
#define	L037(a,b) S("NOTICE %s :ÊÔÍ¼ /êÇ³Æ %s\n",a,b)
#define	L038(a,b) S("NOTICE %s :Çë³¢ÊÔÔ /êÇ³Æ %s-dork.\n",a,b)
#define	L039(a,b) S("PRIVMSG %s :Àë¿ª %s\n",a,b)
#define	L040(a,b) S("PRIVMSG %s :¼ÓÈë%s\n",a,b)
#define	L041(a)	S("PRIVMSG %s :ÇëÖ¸¶¨Ò»¸öêÇ³Æ/ÆµµÀ!\n",a)
#define	L042(a)	S("NOTICE %s :ÊäÈëÒªÉ¾³ıµÄu@h!\n",a)
#define	L043(a) S("NOTICE %s :Ã»ÕÒµ½ÄãËµµÄ½ûÓÃÓÃ»§.\n",a)
#define	L044(a)	S("NOTICE %s :ÊäÈëÒªÉ¾³ıµÄu@h!\n",a)
#define	L045(a) S("NOTICE %s :²»ÄÇÃ´×öĞĞ²»ĞĞ?\n",a)
#define	L046(a)	S("PRIVMSG %s :Êı¾İ¿âÒÑ¾­±¸·İ.\n",a)
#define	L047(a,b) S("NOTICE %s :ÓÃ·¨: %cAUTOTOPIC <Ö÷Ìâ>  (ÉèÖÃÎª\"0\"±íÊ¾Çå¿ÕÖ÷Ìâ)\n",a,b)
#define	L048(a)	S("NOTICE %s :ÓÃ·¨: SETCHAN <ĞÂÆµµÀ>\n",a)
#define	L049(a,b) S("NOTICE %s :È±Ê¡ÆµµÀ: %s\n",a,b)
#define	L050(a)	S("NOTICE %s :ÓÃ·¨: SETCHAR <ĞÂµÄÃüÁî·û>\n",a)
#define	L051(a,b) S("NOTICE %s :ÏÖÔÚµÄÃüÁî·ûÊÇ: %c\n",a,b)
#define	L052(a)	S("NOTICE %s :ÓÃ·¨: SETUSER <ĞÂµÄÓÃ»§ID> (ĞèÒªÖØĞÂÆô¶¯»úÆ÷ÈË)\n",a)
#define	L053(a,b) S("NOTICE %s :ÏÖÔÚµÄÈ±Ê¡ÓÃ»§IDÊÇ: %s\n",a,b)
#define	L054(a)	S("NOTICE %s :ÓÃ·¨: SETNICK <ĞÂµÄêÇ³Æ>\n",a)
#define	L055(a)	S("NOTICE %s :ÓÃ·¨: ADDUSER <#ÆµµÀ> <*user@*.host> <¼¶±ğ> <¿ÚÁî>. ÀıÈç, ADDUSER #darkbot \
*jason@*.superlink.net 3 hisPasswd ... Ê¹ÓÃ#*½«Ê¹¸ÃÓÃ»§µÄÈ¨ÏŞÊÊÓÃÓÚËùÓĞµÄÆµµÀ.\n",a)
#define	L056(a)	sprintf(temp, "Äã»¹Ã»ÓĞÓÃ\2%cSETINFO\2 ÉèÖÃ»¶Ó­ĞÅÏ¢!",a)
#define	L057(a,b,c)	S("NOTICE %s :ÓÃ»§ÒÑÌí¼Ó: %s - ¼¶±ğ%d\n",a,b,c)
#define	L058(a,b,c)	S("NOTICE %s :ÓÃ·¨: %c%s <u@h> [ÀíÓÉ]\n",a,b,c)
#define	L059(a,b,c,d) S("NOTICE %s :¼ÓÈë½ûÓÃÓÃ»§ÁĞ±í#%d, %s; ÀíÓÉ: %s\n",a,b,c,d)
#define	L060(a)	S("NOTICE %s :ÓÃ·¨: REPEAT <number> <delay> <raw-data>\n",a)
#define	L061(a)	S("NOTICE %s :ÒÑÍê³É.\n",a)
#define	L062(a) S("QUIT :ÖØĞÂÆô¶¯ %s ...\n",a);
#define	L064(a,b) S("PRIVMSG %s :%s, ÄãÏëÌí¼ÓÊ²Ã´?\n",a,b)
#define	L064n(a,b) S("NOTICE %s :%s, ÄãÏëÌí¼ÓÊ²Ã´?\n",a,b)
#define	L065(a,b) S("PRIVMSG %s :Ìí¼ÓÊ²Ã´, %s?\n",a,b);
#define	L065n(a,b) S("NOTICE %s :Ìí¼ÓÊ²Ã´, %s?\n",a,b);
#define	L066(a,b,c)	S("PRIVMSG %s :%s: ÒªÌí¼ÓÊ²Ã´ĞÅÏ¢¸ø%s?\n",a,b,c)
#define	L066n(a,b,c) S("NOTICE %s :%s: ÒªÌí¼ÓÊ²Ã´ĞÅÏ¢¸ø%s?\n",a,b,c)
#define	L067(a,b) S("PRIVMSG %s :Ok, %s :)\n",a,b)
#define	L067n(a,b) S("NOTICE %s :Ok, %s :)\n",a,b)
#define	L068(a,b) S("PRIVMSG %s :Ìæ»»Ê²Ã´, %s?\n",a,b)
#define	L069(a,b,c) S("PRIVMSG %s :%s: ÓÃÊ²Ã´ĞÅÏ¢Ìæ»»%s?\n",a,b,c)
#define	L070(a,b,c) S("PRIVMSG %s :%s, %s ÒÑ±»¸üĞÂ.\n",a,b,c)
#define	L071(a,b,c,d) S("PRIVMSG %s :ÓĞ %s %d ½ûÓÃÓÃ»§¼ÇÂ¼%s ÔØÈëÄÚ´æ.\n",a,b,c,d)
#define	L073(a,b,c) S("PRIVMSG %s :%s, »¹ÓĞ%d ÃëÎÒ¾ÍÒªºúÑÔÂÒÓïÁË \n",a,b,c)
#define	L074(a,b,c)	S("PRIVMSG %s :%s: ³¤¶ÈÎª%d×Ö½Ú.\n",a,b,c)
#define	L075(a,b,c,d) S("PRIVMSG %s :%s, ¶ÓÁĞÖĞÏÖÓĞ %d ¼ÇÂ¼%s.\n",a,b,c,d)
#define	L076(a,b) S("PRIVMSG %s :µ½ÏÖÔÚÎÒÒÑ¾­¿´¼û%d¸öÓÃ»§¼ÓÈë.\n",a,b)
#define	L077(a,b,c,d,e)	S("PRIVMSG %s :ÎÒµÄ·şÎñÆ÷ÁĞ±íÖĞÓĞ %s %d ¸ö·şÎñÆ÷%s. ÎÒÏÖÔÚÔÚ\
·şÎñÆ÷ #%d.\n",a,b,c,d,e)
#define	L078(a,b,c)	S("PRIVMSG %s :%s, ÎÒµÄÃüÁî·ûÊÇ: %c\n",a,b,c)
#define	L079(a,b,c)	S("PRIVMSG %s :%sÊ²Ã´, %s?\n",a,b,c)
#define	L080(a,b) S("PRIVMSG %s :%s, ÄãµÃÖ¸¶¨Ò»¸öµØÖ·!\n",a,b)
#define	L081(a,b) S("PRIVMSG %s :ÎŞ·¨²éÕÒ%s.\n",a,b)
#define	L083(a,b,c)	S("PRIVMSG %s :%s: ÄãÏëÈÃÎÒ¸æËß%sÊ²Ã´?\n",a,b,c)
#define	L084(a,b,c)	S("PRIVMSG %s :%s, ¸æËß %s Ê²Ã´?\n",a,b,c)
#define	L085(a,b) S("PRIVMSG %s :¸æËßË­, %s?\n",a,b)
#define	L083n(a,b,c) S("NOTICE %s :%s: ÄãÏëÈÃÎÒ¸æËß%sÊ²Ã´?\n",a,b,c)
#define	L084n(a,b,c) S("NOTICE %s :%s, ¸æËß %s Ê²Ã´?\n",a,b,c)
#define	L085n(a,b) S("NOTICE %s :¸æËßË­, %s?\n",a,b)
#define	L086(a,b) S("PRIVMSG %s :%s\2:\2 ÄãÔÚÎÊÂğ?\n",a,b)
#define	L087(a,b,c,d,e) S("PRIVMSG %s :%s %s %s? ÇëÖØĞÂÊäÈëÃüÁî(´ò %cHELP ¿ÉÒÔ¿´µ½ÓÃ·¨ÌáÊ¾\
hints)\n",a,b,c,d,e)
#define	L086n(a,b) S("NOTICE %s :%s\2:\2 ÄãÔÚÎÊÂğ?\n",a,b)
#define	L087n(a,b,c,d,e) S("NOTICE %s :%s %s %s? ÇëÖØĞÂÊäÈëÃüÁî(´ò %cHELP ¿ÉÒÔ¿´µ½ÓÃ·¨ÌáÊ¾\
hints)\n",a,b,c,d,e)
#define	L088(a) S("QUIT :%s ÒÑ¾­×íÁË!\n",a)
#define	L089(a)	S("PRIVMSG %s :\1ACTION ĞÑÀ´ÁË...\1\n",a)
#define	L090(a,b) S("PRIVMSG %s :ÎÒÕıÔÚ±»¹àË®...ÎÒÍÂ.... \
ÒÑÉ¾³ı%d Ìõ¼ÇÂ¼.\n",a,b)
