#define I_SPEAK "Я говорю по русски."
#define L001(a,b) S("PRIVMSG %s :Не задан пароль, для задания пароля: \2/msg %s PASS \
<старыйпароль> <новыйпароль>\2 (т.к пароль задается впервые, укажите '0' вместо старого пароля)\n",a,b)
#define L002(a,b,c) S("NOTICE %s :Удален permban #%d, %s.\n",a,b,c)
#define L003(a,b) S("NOTICE %s :Не могу открыть %s :(\n",a,b)
#define L004(a,b,c) S("PRIVMSG %s :%s, Я вижу %d SEEN'ов в моей базе.\n",a,b,c)
#define L005(a,b) S("PRIVMSG %s :Ты знаешь больше, чем я, %s.\n",a,b)
#define L006(a,b,c,d) S("PRIVMSG %s :%s, Я не видел %s %s\n",a,b,c,d)
#define L007(a,b) S("NOTICE %s :Autotopic on %s was OFF\n",a,b)
#define L008(a,b) S("NOTICE %s :Autotopic on %s is now OFF\n",a,b);
#define L009(a,b,c) S("NOTICE %s :AUTOTOPIC @ %s ON: %s\n",a,b,c)
#define L010(a,b,c) S("NOTICE %s :AUTOTOPIC @ %s UPDATED: %s\n",a,b,c)
#define L011(a,b,c) S("PRIVMSG %s :%s, готово. Теперь у меня есть %d хохм.\n",a,b,c)
#define L012(a,b) S("NOTICE %s :Пароль для %s обновлен.\n",a,b)
#define L013(a) S("NOTICE %s :Неверный пароль!\n",a)
#define L014(a) S("NOTICE %s :Не могу найти!\n",a)
#define L015(a,b,c,d) S("NOTICE %s :Удален пользователь: %s [%d:%d]\n",a,b,c,d)
#define L016(a,b) S("PRIVMSG %s :%s: Деление на ноль!\n",a,b)
#define L017(a,b) S("PRIVMSG %s :%s: Неверная операция!\n",a,b)
#define L018(a,b,c,d,e) S("KICK %s %s :%s (adding ignore #%d: %s)\n",a,b,c,d,e)
#define L019(a,b,c) S("PRIVMSG %s :Adding ignore #%d: %s!\n",a,b,c);
#define L020(a,b,c,d) S("NOTICE %s :Обновлено #%d: \37[\37%s\37]\37 info\2:\2 %s\n",a,b,c,d)
#define L021(a,b,c,d) S("PRIVMSG %s :%s \37%s\37.. %d записей просмотрено.\n",a,b,c,d)
#define L022(a,b,c) S("PRIVMSG %s :Найдено более, чем \37%d\37 записей, сузьте условия поиска\2:\2 \
%s\n",a,b,c);
#define L023(a,b,c) S("PRIVMSG %s :Я нашел \37одну\37 запись, %s\2:\2 %s\n",a,b,c)
#define L024(a,b,c,d) S("PRIVMSG %s :Я нашел \37%d\37 записей, %s\2:\2 %s\n",a,b,c,d)
#define L025(a,b) S("PRIVMSG %s :Найдено %ld повторяющихся тем. Удалены.\n",a,b)
#define L026(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :Запущен на %s. У меня есть %ld тем в базе данных, Время работы: \
%d дней%s, %02d:%02d, Было задано %ld вопросов, %ld тем добавлено, и %ld тем удалено. \
Время исполнения: %1.4lf секунд%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define L027(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :Запущен на %s. У меня есть %ld тем в базе данных, Время работы: \
%d часов%s, %d минут%s, Было задано %ld вопросов, %ld тем добавлено, и %ld тем удалено. \
Время исполнения: %1.4lf sec%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define L028(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :Запущен на %s. У меня есть %ld тем в базе данных, Время работы: \
%d min%s, %d sec%s, Было задано %ld вопросов, %ld тем добавлено, и %ld тем удалено. \
Время исполнения: %1.4lf sec%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define L029(a,b,c,d) S("PRIVMSG %s :%s: Удалена тема #%ld, \2%s\2.\n",a,b,c,d)
#define L030(a,b,c) S("PRIVMSG %s :%s\2:\2 Не могу найти тему %s. Удаление неудалось.\n",a,b,c)
#define L029n(a,b,c,d) S("NOTICE %s :%s: Удалена тема #%ld, \2%s\2.\n",a,b,c,d)
#define L030n(a,b,c) S("NOTICE %s :%s\2:\2 Не могу найти тему %s. Удаление неудалось.\n",a,b,c)
#define L031(a,b) S("NOTICE %s :Синтаксис: \2/msg %s PASS <oldpass> <newpass>\2\n",a,b)
#define L032(a) Snow("QUIT :У\2\2бит (%s (потому что я так сказал!))\n",a)
#define L033(a) S("NOTICE %s :Синтаксис: UP <#chan> <pass>\n",a)
#define L034(a) S("NOTICE %s :Синтаксис: OP <#chan> [nicks] <pass>\n",a)
#define L035(a) S("NOTICE %s :Синтаксис: DEOP <#chan> [nicks] <pass>\n",a)
#define L036(a) S("NOTICE %s :Укажи ник!\n",a)
#define L037(a,b) S("NOTICE %s :Пытаюсь /nick %s\n",a,b)
#define L038(a,b) S("NOTICE %s :Попробуй /nick %s-dork.\n",a,b)
#define L039(a,b) S("PRIVMSG %s :Покидаю %s\n",a,b)
#define L040(a,b) S("PRIVMSG %s :Соединяюсь с %s\n",a,b)
#define L041(a) S("PRIVMSG %s :Укажи ник/канал!\n",a)
#define L042(a) S("NOTICE %s :Введи u@h для очистки!\n",a)
#define L043(a) S("NOTICE %s :Нет такого бана.\n",a)
#define L044(a) S("NOTICE %s :Введи u@h для удаления!\n",a)
#define L045(a) S("NOTICE %s :Как начсет больше такого не делать?\n",a)
#define L046(a) S("PRIVMSG %s :Сохранили базу данных.\n",a)
#define L047(a,b) S("NOTICE %s :Синтаксис: %cAUTOTOPIC <topic>  (установи в \"0\" чтобы выключить)\n",a,b)
#define L048(a) S("NOTICE %s :Синтаксис: SETCHAN <новые каналы>\n",a)
#define L049(a,b) S("NOTICE %s :Канал по умолчанию: %s\n",a,b)
#define L050(a) S("NOTICE %s :Синтаксис: SETCHAR <новый командный символ>\n",a)
#define L051(a,b) S("NOTICE %s :Новый командный символ теперь: %c\n",a,b)
#define L052(a) S("NOTICE %s :Синтаксис: SETUSER <новый userid> (требуется рестарт)\n",a)
#define L053(a,b) S("NOTICE %s :userid по умолчанию теперь: %s\n",a,b)
#define L054(a) S("NOTICE %s :Синтаксис: SETNICK <новый ник>\n",a)
#define L055(a) S("NOTICE %s :Синтаксис: ADDUSER <#chan> <*user@*.host> <level> <pass>. ie; ADDUSER #darkbot \
*jason@*.superlink.net 3 hisPasswd ... use #* if you want to give access in all chans.\n",a)
#define L056(a) sprintf(temp, "I haven't used \2%cSETINFO\2 yet!",a)
#define L057(a,b,c)     S("NOTICE %s :Добавлен пользователь: %s - уровень %d\n",a,b,c)
#define L058(a,b,c)     S("NOTICE %s :Синтаксис: %c%s <u@h> [причина]\n",a,b,c)
#define L059(a,b,c,d) S("NOTICE %s :Добавлен к permban #%d, %s; причина: %s\n",a,b,c,d)
#define L060(a) S("NOTICE %s :Синтаксис: REPEAT <число> <задержка> <данные>\n",a)
#define L061(a) S("NOTICE %s :Готово.\n",a)
#define L062(a) S("QUIT :Рестартую %s ...\n",a);
#define L064(a,b) S("PRIVMSG %s :%s, что ты хочешь добавить?\n",a,b)
#define L064n(a,b) S("NOTICE %s :%s, что ты хочешь добавить?\n",a,b)
#define L065(a,b) S("PRIVMSG %s :Добавить что, %s?\n",a,b);
#define L066(a,b,c)     S("PRIVMSG %s :%s: Какое приветствие добавить для %s?\n",a,b,c)
#define L067(a,b) S("PRIVMSG %s :Ok, %s :)\n",a,b)
#define L065n(a,b) S("NOTICE %s :Добавить что, %s?\n",a,b);
#define L066n(a,b,c) S("NOTICE %s :%s: Какое приветствие добавить для %s?\n",a,b,c)
#define L067n(a,b) S("NOTICE %s :Ok, %s :)\n",a,b)
#define L068(a,b) S("PRIVMSG %s :Заменить что, %s?\n",a,b)
#define L069(a,b,c) S("PRIVMSG %s :%s: Какая информация должна заменить %s?\n",a,b,c)
#define L070(a,b,c) S("PRIVMSG %s :%s, %s обновлено.\n",a,b,c)
#define L071(a,b,c,d) S("PRIVMSG %s :%s %d permban%s загружено в память.\n",a,b,c,d)
#define L073(a,b,c) S("PRIVMSG %s :%s, %d секунд осталось до следующей хохмы\n",a,b,c)
#define L074(a,b,c)     S("PRIVMSG %s :%s: это было длинной %d символов.\n",a,b,c)
#define L075(a,b,c,d) S("PRIVMSG %s :%s, У меня сейчас %d предметов%s в очереди.\n",a,b,c,d)
#define L076(a,b) S("PRIVMSG %s :Я видел %d присоединяется к нам, пока что.\n",a,b)
#define L077(a,b,c,d,e) S("PRIVMSG %s :%s %d серверов%s в моем списке. Сейчас я на \
сервере #%d.\n",a,b,c,d,e)
#define L078(a,b,c)     S("PRIVMSG %s :%s, мой командный символ: %c\n",a,b,c)
#define L079(a,b,c)     S("PRIVMSG %s :What should i be %sing for, %s?\n",a,b,c)
#define L080(a,b) S("PRIVMSG %s :%s, Необходимо указать адрес!\n",a,b)
#define L081(a,b) S("PRIVMSG %s :Не могу выяснить %s.\n",a,b)
#define L083(a,b,c)     S("PRIVMSG %s :%s: И что мне сказать %s?\n",a,b,c)
#define L084(a,b,c)     S("PRIVMSG %s :%s, Рассказать %s о чем?\n",a,b,c)
#define L085(a,b) S("PRIVMSG %s :Сказать кому, %s?\n",a,b)
#define L083n(a,b,c) S("NOTICE %s :%s: И что мне сказать %s?\n",a,b,c)
#define L084n(a,b,c) S("NOTICE %s :%s, Рассказать %s о чем?\n",a,b,c)
#define L085n(a,b) S("NOTICE %s :Сказать кому, %s?\n",a,b)
#define L086(a,b) S("PRIVMSG %s :%s\2:\2 ты спросил?\n",a,b)
#define L087(a,b,c,d,e) S("PRIVMSG %s :%s %s %s? Перефразируй?  (набери %cHELP для помощи в синтаксисе)\n",a,b,c,d,e)
#define L086n(a,b) S("NOTICE %s :%s\2:\2 ты спросил?\n",a,b)
#define L087n(a,b,c,d,e) S("NOTICE %s :%s %s %s? Перефразируй?  (набери %cHELP для помощи в синтаксисе)\n",a,b,c,d,e)
#define L088(a) S("QUIT :%s замерз!\n",a)
#define L089(a) S("PRIVMSG %s :\1ACTION просныпается...\1\n",a)
#define L090(a,b) S("PRIVMSG %s :Меня флудят. Очищаю выходную очередь. \
%d записей удалено.\n",a,b)
#define Lbadtopic(a,b) S("PRIVMSG %s :Izveni  %s, nu poderjka dla etoy temi bil udalen.\n",a,b);
#define Lbadtopic2(a,b) S("NOTICE %s :Izveni  %s, nu poderjka dla etoy temi bil udalen.\n",a,b);
