#define	I_SPEAK "Jag talar svenska."
#define	L001(a,b) S("PRIVMSG %s :Du har inte satt något lösenord, för att sätta ett lösenord: \2/msg %s PASS \ <gammalt lösendord> <nytt lösenord>\2 (Eftersom det här är den första gången du sätter ett lösenord, använd '0' som ditt gamla lösenord)\n",a,b)
#define	L002(a,b,c) S("NOTICE %s :Tog bort den permanenta bannlysningen #%d, %s.\n",a,b,c)
#define	L003(a,b) S("NOTICE %s :Kan inte öppna %s :(\n",a,b)
#define L004(a,b,c) S("PRIVMSG %s :%s, Det finns %d SEENs i min databas.\n",a,b,c)
#define	L005(a,b) S("PRIVMSG %s :Du vet mer om det än jag, %s.\n",a,b)
#define	L006(a,b,c,d) S("PRIVMSG %s :%s, Jag har inte sett %s %s\n",a,b,c,d)
#define	L007(a,b) S("NOTICE %s :Autotopic på %s var AV\n",a,b)
#define	L008(a,b) S("NOTICE %s :Autotopic på %s är nu AV\n",a,b);
#define	L009(a,b,c) S("NOTICE %s :AUTOTOPIC @ %s PÅ: %s\n",a,b,c)
#define	L010(a,b,c) S("NOTICE %s :AUTOTOPIC @ %s UPPDATERAD: %s\n",a,b,c)
#define	L011(a,b,c) S("PRIVMSG %s :%s, klart. Det finns nu %d slumpsaker.\n",a,b,c)
#define	L012(a,b) S("NOTICE %s :Lösenordet för användare %s är uppdaterat.\n",a,b)
#define	L013(a) S("NOTICE %s :Felaktigt lösenord!\n",a)
#define	L014(a) S("NOTICE %s :Ingen träff!\n",a)
#define	L015(a,b,c,d) S("NOTICE %s :Tog bort användare %s [%d:%d]\n",a,b,c,d)
#define	L016(a,b) S("PRIVMSG %s :%s: Division by zero-fel!\n",a,b)
#define	L017(a,b) S("PRIVMSG %s :%s: Felaktig handling.\n",a,b)
#define	L018(a,b,c,d,e) S("KICK %s %s :%s (ignorerar nu #%d: %s)\n",a,b,c,d,e)
#define	L019(a,b,c) S("PRIVMSG %s :ignorerar nu #%d: %s!\n",a,b,c);
#define L020(a,b,c,d) S("NOTICE %s :Uppdaterade #%d: \37[\37%s\37]\37 info\2:\2 %s\n",a,b,c,d)
#define	L021(a,b,c,d) S("PRIVMSG %s :%s \37%s\37.. %d söktes igenom.\n",a,b,c,d)
#define	L022(a,b,c) S("PRIVMSG %s :Fann mer än \37%d\37 träffar, sök lite mer precist.\2:\2 \ %s\n",a,b,c);
#define	L023(a,b,c) S("PRIVMSG %s :Jag fann \37en\37 träff, %s\2:\2 %s\n",a,b,c)
#define	L024(a,b,c,d) S("PRIVMSG %s :Jag fann \37%d\37 träffar, %s\2:\2 %s\n",a,b,c,d)
#define	L025(a,b) S("PRIVMSG %s :Hittade %ld topic-dubbletter. De togs bort.\n",a,b)
#define	L026(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :Kör %s. Jag har %ld topics i min databas, en upptid på \ %d dagar, %02d:%02d. Det har frågats %ld frågor, lagts till %ld topics, och tagits bort %ld. \ Processtid: %1.4lf sekunder%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define	L027(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :Kör %s. Jag har %ld topics i min databas, Upptid: \ %d timmar och %d minuter%s. Det har frågats %ld frågor, lagts till %ld topics och tagits bort %ld. \ Processtid: %1.4lf sekunder%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define	L028(a,b,c,d,e,f,g,h,i,j,k,l) S("PRIVMSG %s :Kör %s. Jag har %ld topics i min databas, Upptid: \ %d minuter%s, %d sekunder%s. Det har frågats %ld frågor, lagts till %ld topics och tagits bort %ld. \ Processtid: %1.4lf sekunder%s\n",a,b,c,d,e,f,g,h,i,j,k,l)
#define	L029(a,b,c,d) S("PRIVMSG %s :%s: Jag tog bort topic #%ld, \2%s\2.\n",a,b,c,d)
#define	L030(a,b,c) S("PRIVMSG %s :%s\2:\2 Jag hittade inte topicen %s. Radering misslyckades.\n",a,b,c)
#define	L029n(a,b,c,d) S("NOTICE %s :%s: Jag tog bort topic #%ld, \2%s\2.\n",a,b,c,d)
#define	L030n(a,b,c) S("NOTICE %s :%s\2:\2 Jag hittade inte topicen %s. Radering misslyckades.\n",a,b,c)
#define	L031(a,b) S("NOTICE %s :Syntax: \2/msg %s PASS <gammalt lösenord> <nytt lösenord>\2\n",a,b)
#define	L032(a)	Snow("QUIT :D\2\2ödad (%s (För att jag säger det!))\n",a)
#define	L033(a)	S("NOTICE %s :Syntax: UP <#kanal> <lösenord>\n",a)
#define	L034(a)	S("NOTICE %s :Syntax: OP <#kanal> [namn] <lösenord>\n",a)
#define	L035(a)	S("NOTICE %s :Syntax: DEOP <#kanal> [namn] <lösenord>\n",a)
#define	L036(a)	S("NOTICE %s :Ange ett namn!\n",a)
#define	L037(a,b) S("NOTICE %s :Försöker med /nick %s\n",a,b)
#define	L038(a,b) S("NOTICE %s :Försök med /nick %s-pucko.\n",a,b)
#define	L039(a,b) S("PRIVMSG %s :Lämnar %s\n",a,b)
#define	L040(a,b) S("PRIVMSG %s :Går in i %s\n",a,b)
#define	L041(a)	S("PRIVMSG %s :Ange ett namn/kanal!\n",a)
#define	L042(a)	S("NOTICE %s :Skriv den u@h du vill rensa bort. \n",a)
#define	L043(a) S("NOTICE %s :Det finns ingen sådan bannlysning.\n",a)
#define	L044(a)	S("NOTICE %s :Skriv vilken u@h du vill ta bort.\n",a)
#define	L045(a) S("NOTICE %s :Hur vore det om jag inte gjorde så?\n",a)
#define	L046(a)	S("PRIVMSG %s :Sparade databasen.\n",a)
#define	L047(a,b) S("NOTICE %s :SYNTAX: %cAUTOTOPIC <topic>  (sätt till \"0\" för att stänga av)\n",a,b)
#define	L048(a)	S("NOTICE %s :Syntax: SETCHAN <nya kanaler>\n",a)
#define	L049(a,b) S("NOTICE %s :Default-kanal: %s\n",a,b)
#define	L050(a)	S("NOTICE %s :Syntax: SETCHAR <nytt kommandotecken>\n",a)
#define	L051(a,b) S("NOTICE %s :Nytt kommandotecken: %c\n",a,b)
#define	L052(a)	S("NOTICE %s :Syntax: SETUSER <ny användarid> (kräver en omstart)\n",a)
#define	L053(a,b) S("NOTICE %s :Default-användarid är nu: %s\n",a,b)
#define	L054(a)	S("NOTICE %s :Syntax: SETNICK <nytt namn>\n",a)
#define	L055(a)	S("NOTICE %s :Syntax: ADDUSER <#kanal>
< *anv ä ndare @ *.v ä rddator.se > <niv å ><l ö senord >.t.ex;
ADDUSER
#darkbot \ *jason@*.superlink.net 3 hansLösenord ... använd #* om du vill ge tillgång till alla kanaler.\n",a)
#define	L056(a)	sprintf(temp, "Jag har inte använt \2%cSETINFO\2 ännu!",a)
#define	L057(a,b,c)	S("NOTICE %s :La till användare: %s - nivå %d\n",a,b,c)
#define	L058(a,b,c)	S("NOTICE %s :Syntax: %c%s <u@h> [anledning]\n",a,b,c)
#define	L059(a,b,c,d) S("NOTICE %s :Lade till i den permanenta bannlysningslistan: #%d, %s; anledning: %s\n",a,b,c,d)
#define	L060(a)	S("NOTICE %s :Syntax: REPEAT <nummer> <fördröjning> <rådata>\n",a)
#define	L061(a)	S("NOTICE %s :Klart.\n",a)
#define	L062(a) S("QUIT :Startar om %s ...\n",a);
#define	L064(a,b) S("PRIVMSG %s :%s, vad vill du lägga till?\n",a,b)
#define	L064n(a,b) S("NOTICE %s :%s, vad vill du lägga till?\n",a,b)
#define	L065(a,b) S("PRIVMSG %s :Lägga till vad, %s?\n",a,b);
#define	L066(a,b,c)	S("PRIVMSG %s :%s: Vilken information ska läggas till för %s?\n",a,b,c)
#define	L067(a,b) S("PRIVMSG %s :Okej, %s :)\n",a,b)
#define	L065n(a,b) S("NOTICE %s :Lägga till vad, %s?\n",a,b);
#define	L066n(a,b,c) S("NOTICE %s :%s: Vilken information ska läggas till för %s?\n",a,b,c)
#define	L067n(a,b) S("NOTICE %s :Okej, %s :)\n",a,b)
#define	L068(a,b) S("PRIVMSG %s :Byta ut vad, %s?\n",a,b)
#define	L069(a,b,c) S("PRIVMSG %s :%s: Vilken information skulle jag byta ut %s?\n",a,b,c)
#define	L070(a,b,c) S("PRIVMSG %s :%s, %s är uppdaterad.\n",a,b,c)
#define	L071(a,b,c,d) S("PRIVMSG %s :Det finns %s %d permanenta bannlysningar%s laddade i ram-minnet.\n",a,b,c,d)
#define	L073(a,b,c) S("PRIVMSG %s :%s, %d sekunder kvar till en slumpsak.\n",a,b,c)
#define	L074(a,b,c)	S("PRIVMSG %s :%s: den var %d tecken lång.\n",a,b,c)
#define	L075(a,b,c,d) S("PRIVMSG %s :%s, De finns för närvarande %d saker%s i kö.\n",a,b,c,d)
#define	L076(a,b) S("PRIVMSG %s :Jag har sett %d folk som kommit hit än så länge.\n",a,b)
#define	L077(a,b,c,d,e)	S("PRIVMSG %s :Det finns %s %d server%s i min serverlista. Jag är för närvarande på \
	server
#%d.\n",a,b,c,d,e)
#define	L078(a,b,c)	S("PRIVMSG %s :%s, mitt kommandotecken är: %c\n",a,b,c)
#define	L079(a,b,c)	S("PRIVMSG %s :Vad ska jag %sing för, %s?\n",a,b,c)
#define	L080(a,b) S("PRIVMSG %s :%s, du måste ange en address!\n",a,b)
#define	L081(a,b) S("PRIVMSG %s :Kunde inte kolla upp %s.\n",a,b)
#define	L083(a,b,c)	S("PRIVMSG %s :%s: Vad vill du att jag ska säga %s?\n",a,b,c)
#define	L084(a,b,c)	S("PRIVMSG %s :%s, Berätta för %s om vad?\n",a,b,c)
#define	L085(a,b) S("PRIVMSG %s :Säga till vem, %s?\n",a,b)
#define	L083n(a,b,c) S("NOTICE %s :%s: Vad vill du att jag ska säga %s?\n",a,b,c)
#define	L084n(a,b,c) S("NOTICE %s :%s, Berätta för %s om vad?\n",a,b,c)
#define	L085n(a,b) S("NOTICE %s :Säga till vem, %s?\n",a,b)
#define	L086(a,b) S("PRIVMSG %s :%s\2:\2 du frågade mig?\n",a,b)
#define	L087(a,b,c,d,e) S("PRIVMSG %s :%s %s %s? Vill du omformulera det där?  (Skriv %cHELP för syntax-tips)\n",a,b,c,d,e)
#define	L086n(a,b) S("NOTICE %s :%s\2:\2 du frågade mig?\n",a,b)
#define	L087n(a,b,c,d,e) S("NOTICE %s :%s %s %s? Vill du omformulera det där?  (Skriv %cHELP för syntax-tips)\n",a,b,c,d,e)
#define	L088(a) S("QUIT :%s är brutalt hög!\n",a)
#define	L089(a)	S("PRIVMSG %s :\1ACTION vaknar upp...\1\n",a)
#define	L090(a,b) S("PRIVMSG %s :Jag blir floodad. Dumpar kön. \
%d saker togs bort.\n",a,b)
#define Lbadtopic(a,b) S("PRIVMSG %s :Tyvärr  %s, support för det området har tagits bort.\n",a,b);
#define Lbadtopic2(a,b) S("NOTICE %s :Tyvärr  %s, support för det området har tagits bort.\n",a,b);